### ISSUE TITLE
NeuQuant creates transparency from non-transparency

### ISSUE THREAD

**Issue by jtlapp** [ibezkrovnyi/image-quantization#10]
I ran [this gradient PNG](http://leeoniya.github.io/RgbQuant.js/demo/img/sculptmap.png) through NeuQuant for 256 colors, Euclidean, and NearestColor, and I got dozens of pixels with alpha 0xFE. All pixels have alpha 0xFF in the source image.

Other than that, NeuQuant seems to do a nicer job than RGBQuant.

UPDATE: NeuQuantFloat doesn't have this problem, **AND IT'S WICKED FAST!**

**Comment by leeoniya** [comment]
RgbQuant was originally designed for graphics, so without tweaking it will do worse an photos and gradients but it does better in color accuracy in many cases where neuquant pics poor colors. it really depends on the types of images you're working with. for example, if you quantize an image with 256 colors, neuquant will give you a pallete of 256 *different* colors, whereas rgbquant will give you the exact originals :)

**Comment by jtlapp** [comment]
Oh wow. That's interesting, and great to know. I guess that means I have to expose this option in my API. (I'm adding color reduction to [`gifwrap`](https://github.com/jtlapp/gifwrap).) Thanks for that tidbit!

**Comment by leeoniya** [comment]
RgbQuant was also built for multi-frame gif encoding. i also used omggif :)

https://github.com/leeoniya/GIFter.js

**Comment by jtlapp** [comment]
Oh cool! You're ahead of me in many ways. Mine only runs on node at the moment, but I need a webworker solution. Low priority for me at the moment. I'll have to study what you did. Thanks!

Also, you'll want to update omggif, as I found some bugs in it, which the repo owner promptly fixed.

**Comment by jtlapp** [comment]
Any hey! We both opted for punny package names!
