### ISSUE TITLE
Add rgbQuant DithDelta option

### ISSUE THREAD

**Issue by pixelplanetdev** [ibezkrovnyi/image-quantization#79]
I am currently stuck rgbQuant because it has a dithDelta option:
`dithering threshhold (0-1) e.g: 0.05 will not dither colors with <= 5% difference`
This option is very handy and i would have switched to image-q if i would figure out a way how to do the same with it.

**Comment by ibezkrovnyi** [comment]
Equivalent of `dithDelta` in `image-q` is `minimumColorDistanceToDither` parameter passed to `iq.image.ErrorDiffusionArray` constructor:

![image](https://user-images.githubusercontent.com/1188919/132983879-e3ab6daf-e144-4faf-b6c3-ed6b01e8c4b1.png)

In `demo` project it is set to 0: https://github.com/ibezkrovnyi/image-quantization/blob/15583cb577f6494db027f476491bd8f79483148e/packages/demo/src/controller/usage.ts#L135-L140

It would be nice if you could share the _example image_ and _quantization parameters_ where this parameter helps.

**Comment by pixelplanetdev** [comment]
Thanks,
my specific usecase were images that were already close to the target colors.
Like when someone saves an image that is already reduced to our palette and the colors get shifted for some reason (like color profiles), he edits it and then puts it into the converter again, and it would suddenly dither stuff that it shouldn't.
With rgbQuant i offered a slider to set the threshold and it got used a lot.

But i switched to image-q even without that a year ago, so it didn't stop me from using this great project here.
