### ISSUE TITLE
fn/set-immediate moved to features/set-immediate

### ISSUE THREAD

**Issue by pixelplanetdev** [ibezkrovnyi/image-quantization#80]
set-immediate cannot be resolved in projects with updated core-js because it moved from fn to features.
Rewriting the inmports fixes this.

**Comment by Dylan190774** [comment]
Could you please tell me how I can fix this? 
When I change it in all necessary files the `dist` folder in `node_modules `it gets immediately overwritten again.
I already forked the project and made the changes, but I don't know how to add this fork instead of the master.

**Comment by ibezkrovnyi** [comment]
- `image-q@3.0.3` has `core-js` built-in into `umd` build (used for `require` as well)

- `image-q@3.0.4` has no dependency on `core-js` :sunglasses:. Promises and a few other EcmaScript features are expected to be polyfilled (if needed) by consumers now. 

Feedback is welcome

**Comment by ibezkrovnyi** [comment]
fixed in image-q@3.0.3 & image-q@3.0.4
