### ISSUE TITLE
Where is the documentation ?

### ISSUE THREAD

**Issue by positiv-prod** [ibezkrovnyi/image-quantization#89]
Hello,

I know it's a silly question but your module has a documentation ? I didn't find the Read.md file ...

Many thanks ...

**Comment by ibezkrovnyi** [comment]
Project's README is here atm: https://github.com/ibezkrovnyi/image-quantization/tree/main/packages/image-q

README in the root need to be created.

**Comment by ibezkrovnyi** [comment]
Fixed in #91
