### ISSUE TITLE
Errors in the README example

### ISSUE THREAD

**Issue by jtlapp** [ibezkrovnyi/image-quantization#9]
This module is absolutely fantastic! It's working well for me so far. Wiring it up was a bit of a challenge, as I had to frequently browse the source code. But the source is clear enough to do it.

I did find two errors in your README examples. The following:

```js
var paletteQuantizer = new iq.palette.RgbQuant(distanceCalculator, targetColors);
```

Should have a capital `RGB` in `RGBQuant`:

```js
var paletteQuantizer = new iq.palette.RGBQuant(distanceCalculator, targetColors);
```

And the variable has the wrong name here:

```js
var imageDitherer = new iq.image.NearestColor(distanceCalculator);
var resultPointContainer = imageQuantizer.quantize(pointContainer, palette);
```

I'm thinking you mean:

```js
var imageQuantizer = new iq.image.NearestColor(distanceCalculator);
var resultPointContainer = imageQuantizer.quantize(pointContainer, palette);
```

Thank you so much for putting this together!

**Comment by ibezkrovnyi** [comment]
```ts
var imageDitherer = new iq.image.NearestColor(distanceCalculator);
var resultPointContainer = imageQuantizer.quantize(pointContainer, palette);
```

^^^ I mean `var resultPointContainer = imageDitherer.quantize(pointContainer, palette);`

Thanks for reporting this issue 👍 

Code quality/suggestions reports are welcome too!
