### ISSUE TITLE
is 'demo' folder required?

### ISSUE THREAD

**Issue by NDietrich** [ibezkrovnyi/image-quantization#90]
Hello,
I'm wondering if the 'demo' folder is required or can be deleted. This module is a dependency of one of my projects, and I'm looking to reduce the size of my project, and this demo folder is the largest folder by far. If it's not required, then I should be able to safely remove it.

thank you.

**Comment by ibezkrovnyi** [comment]
Hi Noah,
Cold you please clarify what 'demo' folder do you mean?

**Comment by NDietrich** [comment]
hello,
when I use npm to install this library, it includes a 'demo' folder. 
**Note** I'm using 1.1.1 of image-q (it is a sub-requisite of another project so I don't have a choice on updating the version.

I run:  
`npm install image-q@1.1.1 --production=true`

I then navigate into the node_modules folder:
`cd node_modules\image-q`

check contents:
```noah@comp:~/tmp/node_modules/image-q$ ls -l
total 104
drwxrwxr-x 4 noah noah  4096 Dez 26 06:32 demo
drwxrwxr-x 9 noah noah  4096 Dez 26 06:32 dist
-rw-rw-r-- 1 noah noah  2298 Jun 26  2015 LICENSE
-rw-rw-r-- 1 noah noah  1976 Dez 26 06:32 package.json
-rw-rw-r-- 1 noah noah 64602 Jun 26  2015 quantization.png
-rw-rw-r-- 1 noah noah 10913 Aug 28  2016 README.md
drwxrwxr-x 9 noah noah  4096 Dez 26 06:32 src
-rw-rw-r-- 1 noah noah   275 Jun 16  2015 tasks.txt
drwxrwxr-x 4 noah noah  4096 Dez 26 06:32 test
```
and you see there is a **demo** folder. I'm wondering if I can delete the demo folder as it's quite large (relatively) at 14 MB.

thank you

**Comment by ibezkrovnyi** [comment]
Hello, thank you for the details!

Yes, feel free to delete `demo` folder if you absolutely need to stay on image-q@1.1.1. `demo` folder was included into package by mistake.

However I suggest to move to image-q@4.0.0+.
