### ISSUE TITLE
can't build using create react app 4

### ISSUE THREAD

**Issue by elmariachi111** [ibezkrovnyi/image-quantization#92]
cannot import image-q from an app that's built on Create React App 4.

created a demo: https://github.com/elmariachi111/esm-err-imageq

`npm run start` yields:

```
./node_modules/image-q/dist/esm/src/image/nearestColor.js 11:11
Module parse failed: Unexpected token (11:11)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| import { ProgressTracker } from '../utils/progressTracker';
| export class NearestColor extends AbstractImageQuantizer {
>   _distance;
| 
|   constructor(colorDistanceCalculator) {
```

Have parsed through your ts config. Assume this isn't working because the emitted js files are built for esnext and that's not supported by the webpack config of CRA (4). Btw it does build on the brand new CRA 5 but this one dropped support for node types and the whole web3 industry depends on them so upgrading atm isn't an option. Any ideas?

**Comment by elmariachi111** [comment]
When "convincing" babel by [hacking the browserslist](https://stackoverflow.com/questions/67552020/how-to-fix-error-failed-to-compile-node-modules-react-leaflet-core-esm-pat) the next issue is 

```
/..../node_modules/.pnpm/image-q@2.1.2/node_modules/image-q/dist/esm/basicAPI.js
Module not found: Can't resolve 'core-js/fn/set-immediate' in '..../node_modules/.pnpm/image-q@2.1.2/node_modules/image-q/dist/esm'
```

**Comment by elmariachi111** [comment]
think it might help to set the tsconfig's `target` to `es6`

**Comment by pixelplanetdev** [comment]
The set-immediate is an issue in the older version,
consider updating to the current one and it should work.

**Comment by ibezkrovnyi** [comment]
@elmariachi111 
- Issue with core-js [is fixed](https://github.com/ibezkrovnyi/image-quantization/blob/main/README.md#304)
- Latest version of image-q still can't be used in your demo

`esm` build in image-q is actually not compatible with real ES Modules, only tools like webpack can consume it.

**Comment by ibezkrovnyi** [comment]
@elmariachi111 could you please check `image-q@4.0.0` if it works for you?

**Comment by elmariachi111** [comment]
@ibezkrovnyi just updated all our dependencies and 4.0.0 runs nicely inside a browser and a node context at the same time now. Nice work, thanks a lot, highly appreciated! That's my adapted repo for React: https://github.com/elmariachi111/esm-err-imageq/commit/9d17b93d04fe80de780452b63cbedfc5857dfa57
