### ISSUE TITLE
PointContainer.fromHTMLImageElement returns empty pointContainer in >=3.0.x

### ISSUE THREAD

**Issue by pixelplanetdev** [ibezkrovnyi/image-quantization#93]
I quantize an image from an HTML Image Element to a given palette like this:
```js
const image = <HTMLImageElement>;
const colors = [[r, g, b], [r, g, b], ...];

const palette = new utils.Palette();
palette.add(utils.Point.createByRGBA(0, 0, 0, 0));
for (let i = 0; i < colors.length; i += 1) {
  const [r, g, b] = colors[i];
  const point = utils.Point.createByRGBA(r, g, b, 255);
  palette.add(point);
});

const inputPointContainer = utils.PointContainer.fromHTMLImageElement(image);

const outputPointContainer = await applyPalette(inputPointContainer, palette, {
  colorDistanceFormula: 'euclidean',
  imageQuantization: 'nearest',
  onProgress: (progress) => {
    //print progress somewhere
  },
});
```

It worked fine in 2.1.2, but since 3.0.x it takes three times as long and returns an a PointContainer with the right size, but with all pixels being r: 0, g: 0, b: 0, a: 0.

![empty-point-container](https://user-images.githubusercontent.com/59449392/147850031-d8db6c1c-558d-4f8a-8d83-371f62e4a429.png)
(same image takes about 360ms for PointContainer.fromHTMLImageElement in 2.1.2)

**Comment by ibezkrovnyi** [comment]
Cannot reproduce this with random palette and random image file (tried both JPG and PNG) of the same size (877x855).

PR #94, check /examples/HTMLImageElement project.

**Comment by pixelplanetdev** [comment]
Thanks. I am using babel and webpack and i think that the issue is related with that.

I tried to populate the pointContainer myself with:

```
function createPointContainerFromImageData(imageData) {
  const { width, height, data } = imageData;
  console.log('create container from image data', data);
  const pointContainer = new utils.PointContainer();
  pointContainer.setWidth(width);
  pointContainer.setHeight(height);
  const pointArray = pointContainer.getPointArray();
  let i = 0;
  while (i < data.length) {
    const point = utils.Point.createByRGBA(
      data[i++],
      data[i++],
      data[i++],
      data[i++],
    );
    if (i < 25) console.log('point', point);
    pointArray.push(point);
  }
  console.log('pointArray', pointArray);
  return pointContainer;
}
```

And the points all set to 0 after they are pushed into the pointArray.

The first five console logged points all have values, but then in the console logged pointArray they are r: 0, g: 0, b: 0, a: 0.

I will create some minimal project to reproduce it in a proper way.

**Comment by pixelplanetdev** [comment]
I tried hard to recreate it with a new minimal project, but i couldn't. Even with the same babel and webpack and react configurations, it didn't happen there.

So i tried to track it down in my project where it happens, and it seems like the _kX values in the colorDistance formulas aren't being set. Or they are getting set and being unset again for some reason.

![delete](https://user-images.githubusercontent.com/59449392/147886463-413dfae8-d71d-4889-8005-7822a525d239.png)

So i now just manually call _setDefaults and it works now.
I have no clue and i spent too much time on this, so i will leave it like that
https://github.com/pixelplanetdev/pixelplanet/blob/8c17f56b792ed1448ed36316fecea472981cfb86/src/utils/image.js#L148

You can close this if you like.

**Comment by pixelplanetdev** [comment]
its a different issue than i thought it is, will close this in favor of a new report
